//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.MassServis")]
    public interface MassServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/LoginValidacija", ReplyAction="http://tempuri.org/MassServis/LoginValidacijaResponse")]
        int LoginValidacija(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/LoginValidacija", ReplyAction="http://tempuri.org/MassServis/LoginValidacijaResponse")]
        System.Threading.Tasks.Task<int> LoginValidacijaAsync(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UnesiDobavljaca", ReplyAction="http://tempuri.org/MassServis/UnesiDobavljacaResponse")]
        void UnesiDobavljaca(Mass.Data.lieferant dobavljac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UnesiDobavljaca", ReplyAction="http://tempuri.org/MassServis/UnesiDobavljacaResponse")]
        System.Threading.Tasks.Task UnesiDobavljacaAsync(Mass.Data.lieferant dobavljac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaDobavljaca", ReplyAction="http://tempuri.org/MassServis/ListaDobavljacaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.lieferant> ListaDobavljaca();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaDobavljaca", ReplyAction="http://tempuri.org/MassServis/ListaDobavljacaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.lieferant>> ListaDobavljacaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ObrisiDobavljaca", ReplyAction="http://tempuri.org/MassServis/ObrisiDobavljacaResponse")]
        void ObrisiDobavljaca(int brDobavljaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ObrisiDobavljaca", ReplyAction="http://tempuri.org/MassServis/ObrisiDobavljacaResponse")]
        System.Threading.Tasks.Task ObrisiDobavljacaAsync(int brDobavljaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UpdateDobavljac", ReplyAction="http://tempuri.org/MassServis/UpdateDobavljacResponse")]
        void UpdateDobavljac(Mass.Data.lieferant d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UpdateDobavljac", ReplyAction="http://tempuri.org/MassServis/UpdateDobavljacResponse")]
        System.Threading.Tasks.Task UpdateDobavljacAsync(Mass.Data.lieferant d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UnesiRadnika", ReplyAction="http://tempuri.org/MassServis/UnesiRadnikaResponse")]
        void UnesiRadnika(
                    int broj, 
                    int titula, 
                    string ime, 
                    string prezime, 
                    string adresa, 
                    string tel1, 
                    string tel2, 
                    string mobitel, 
                    string fax, 
                    string skype, 
                    string email, 
                    float zarada, 
                    float satnica, 
                    string odmor, 
                    string odmor_na, 
                    float broj_plate, 
                    string bolovanje, 
                    string banka, 
                    string blz, 
                    string bic, 
                    string KtoNr, 
                    string Iban, 
                    string vlasnik, 
                    string biljeske, 
                    System.DateTime datum, 
                    int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UnesiRadnika", ReplyAction="http://tempuri.org/MassServis/UnesiRadnikaResponse")]
        System.Threading.Tasks.Task UnesiRadnikaAsync(
                    int broj, 
                    int titula, 
                    string ime, 
                    string prezime, 
                    string adresa, 
                    string tel1, 
                    string tel2, 
                    string mobitel, 
                    string fax, 
                    string skype, 
                    string email, 
                    float zarada, 
                    float satnica, 
                    string odmor, 
                    string odmor_na, 
                    float broj_plate, 
                    string bolovanje, 
                    string banka, 
                    string blz, 
                    string bic, 
                    string KtoNr, 
                    string Iban, 
                    string vlasnik, 
                    string biljeske, 
                    System.DateTime datum, 
                    int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaRadnika", ReplyAction="http://tempuri.org/MassServis/ListaRadnikaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.mitarbeiter> ListaRadnika();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaRadnika", ReplyAction="http://tempuri.org/MassServis/ListaRadnikaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.mitarbeiter>> ListaRadnikaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UnesiKupca", ReplyAction="http://tempuri.org/MassServis/UnesiKupcaResponse")]
        void UnesiKupca(Mass.Data.kunden kupac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UnesiKupca", ReplyAction="http://tempuri.org/MassServis/UnesiKupcaResponse")]
        System.Threading.Tasks.Task UnesiKupcaAsync(Mass.Data.kunden kupac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ComboKorisnici", ReplyAction="http://tempuri.org/MassServis/ComboKorisniciResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.user> ComboKorisnici();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ComboKorisnici", ReplyAction="http://tempuri.org/MassServis/ComboKorisniciResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.user>> ComboKorisniciAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ComboKorisniciPoruke", ReplyAction="http://tempuri.org/MassServis/ComboKorisniciPorukeResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.user> ComboKorisniciPoruke(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ComboKorisniciPoruke", ReplyAction="http://tempuri.org/MassServis/ComboKorisniciPorukeResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.user>> ComboKorisniciPorukeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaKupaca", ReplyAction="http://tempuri.org/MassServis/ListaKupacaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.kunden> ListaKupaca();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaKupaca", ReplyAction="http://tempuri.org/MassServis/ListaKupacaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.kunden>> ListaKupacaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ObrisiKupca", ReplyAction="http://tempuri.org/MassServis/ObrisiKupcaResponse")]
        void ObrisiKupca(int brKupca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ObrisiKupca", ReplyAction="http://tempuri.org/MassServis/ObrisiKupcaResponse")]
        System.Threading.Tasks.Task ObrisiKupcaAsync(int brKupca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UpdateKupac", ReplyAction="http://tempuri.org/MassServis/UpdateKupacResponse")]
        void UpdateKupac(Mass.Data.kunden k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UpdateKupac", ReplyAction="http://tempuri.org/MassServis/UpdateKupacResponse")]
        System.Threading.Tasks.Task UpdateKupacAsync(Mass.Data.kunden k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UnesiUsera", ReplyAction="http://tempuri.org/MassServis/UnesiUseraResponse")]
        void UnesiUsera(string Name, string LastName, string Email, string Telefon, bool Aktivan, string Slika, string Username, string Password, int UserType, bool Pocetna, string Licence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UnesiUsera", ReplyAction="http://tempuri.org/MassServis/UnesiUseraResponse")]
        System.Threading.Tasks.Task UnesiUseraAsync(string Name, string LastName, string Email, string Telefon, bool Aktivan, string Slika, string Username, string Password, int UserType, bool Pocetna, string Licence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaUserView", ReplyAction="http://tempuri.org/MassServis/ListaUserViewResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_User_ViewResult> ListaUserView();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaUserView", ReplyAction="http://tempuri.org/MassServis/ListaUserViewResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_User_ViewResult>> ListaUserViewAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getUsersView", ReplyAction="http://tempuri.org/MassServis/getUsersViewResponse")]
        System.Data.DataSet getUsersView();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getUsersView", ReplyAction="http://tempuri.org/MassServis/getUsersViewResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getUsersViewAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/DeleteRadnik", ReplyAction="http://tempuri.org/MassServis/DeleteRadnikResponse")]
        void DeleteRadnik(int sifraRadnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/DeleteRadnik", ReplyAction="http://tempuri.org/MassServis/DeleteRadnikResponse")]
        System.Threading.Tasks.Task DeleteRadnikAsync(int sifraRadnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UpdateRadnika", ReplyAction="http://tempuri.org/MassServis/UpdateRadnikaResponse")]
        void UpdateRadnika(Mass.Data.mitarbeiter r, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UpdateRadnika", ReplyAction="http://tempuri.org/MassServis/UpdateRadnikaResponse")]
        System.Threading.Tasks.Task UpdateRadnikaAsync(Mass.Data.mitarbeiter r, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/VratiKorisnika", ReplyAction="http://tempuri.org/MassServis/VratiKorisnikaResponse")]
        Mass.Data.user VratiKorisnika(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/VratiKorisnika", ReplyAction="http://tempuri.org/MassServis/VratiKorisnikaResponse")]
        System.Threading.Tasks.Task<Mass.Data.user> VratiKorisnikaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/EditujUsera", ReplyAction="http://tempuri.org/MassServis/EditujUseraResponse")]
        void EditujUsera(int idUser, string Name, string LastName, string Email, string Telefon, bool Aktivan, string Slika, string Username, string Password, int UserType, bool Pocetna, string Licence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/EditujUsera", ReplyAction="http://tempuri.org/MassServis/EditujUseraResponse")]
        System.Threading.Tasks.Task EditujUseraAsync(int idUser, string Name, string LastName, string Email, string Telefon, bool Aktivan, string Slika, string Username, string Password, int UserType, bool Pocetna, string Licence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UpdateKorisnik", ReplyAction="http://tempuri.org/MassServis/UpdateKorisnikResponse")]
        void UpdateKorisnik(Mass.Data.user k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UpdateKorisnik", ReplyAction="http://tempuri.org/MassServis/UpdateKorisnikResponse")]
        System.Threading.Tasks.Task UpdateKorisnikAsync(Mass.Data.user k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/DeleteUser", ReplyAction="http://tempuri.org/MassServis/DeleteUserResponse")]
        void DeleteUser(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/DeleteUser", ReplyAction="http://tempuri.org/MassServis/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/PretraziRadnika", ReplyAction="http://tempuri.org/MassServis/PretraziRadnikaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.mitarbeiter> PretraziRadnika(string ime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/PretraziRadnika", ReplyAction="http://tempuri.org/MassServis/PretraziRadnikaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.mitarbeiter>> PretraziRadnikaAsync(string ime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/PretraziDobavljaca", ReplyAction="http://tempuri.org/MassServis/PretraziDobavljacaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.lieferant> PretraziDobavljaca(string ime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/PretraziDobavljaca", ReplyAction="http://tempuri.org/MassServis/PretraziDobavljacaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.lieferant>> PretraziDobavljacaAsync(string ime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/changeUserPocetnaOrAktivan", ReplyAction="http://tempuri.org/MassServis/changeUserPocetnaOrAktivanResponse")]
        void changeUserPocetnaOrAktivan(int tip, int idUser, bool value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/changeUserPocetnaOrAktivan", ReplyAction="http://tempuri.org/MassServis/changeUserPocetnaOrAktivanResponse")]
        System.Threading.Tasks.Task changeUserPocetnaOrAktivanAsync(int tip, int idUser, bool value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ChangeWorkerStatus", ReplyAction="http://tempuri.org/MassServis/ChangeWorkerStatusResponse")]
        void ChangeWorkerStatus(int idRadnika, bool status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ChangeWorkerStatus", ReplyAction="http://tempuri.org/MassServis/ChangeWorkerStatusResponse")]
        System.Threading.Tasks.Task ChangeWorkerStatusAsync(int idRadnika, bool status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/unesiBug", ReplyAction="http://tempuri.org/MassServis/unesiBugResponse")]
        void unesiBug(string bugText, int idUser, bool status, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/unesiBug", ReplyAction="http://tempuri.org/MassServis/unesiBugResponse")]
        System.Threading.Tasks.Task unesiBugAsync(string bugText, int idUser, bool status, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaBugova", ReplyAction="http://tempuri.org/MassServis/ListaBugovaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.bug> ListaBugova();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaBugova", ReplyAction="http://tempuri.org/MassServis/ListaBugovaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.bug>> ListaBugovaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/changeBugStatus", ReplyAction="http://tempuri.org/MassServis/changeBugStatusResponse")]
        void changeBugStatus(string datum, bool statusValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/changeBugStatus", ReplyAction="http://tempuri.org/MassServis/changeBugStatusResponse")]
        System.Threading.Tasks.Task changeBugStatusAsync(string datum, bool statusValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/DeleteBug", ReplyAction="http://tempuri.org/MassServis/DeleteBugResponse")]
        void DeleteBug(string datum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/DeleteBug", ReplyAction="http://tempuri.org/MassServis/DeleteBugResponse")]
        System.Threading.Tasks.Task DeleteBugAsync(string datum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/MitarbeiterNr", ReplyAction="http://tempuri.org/MassServis/MitarbeiterNrResponse")]
        int MitarbeiterNr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/MitarbeiterNr", ReplyAction="http://tempuri.org/MassServis/MitarbeiterNrResponse")]
        System.Threading.Tasks.Task<int> MitarbeiterNrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/LieferantNr", ReplyAction="http://tempuri.org/MassServis/LieferantNrResponse")]
        int LieferantNr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/LieferantNr", ReplyAction="http://tempuri.org/MassServis/LieferantNrResponse")]
        System.Threading.Tasks.Task<int> LieferantNrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/KundenNr", ReplyAction="http://tempuri.org/MassServis/KundenNrResponse")]
        int KundenNr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/KundenNr", ReplyAction="http://tempuri.org/MassServis/KundenNrResponse")]
        System.Threading.Tasks.Task<int> KundenNrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/AngebotNr", ReplyAction="http://tempuri.org/MassServis/AngebotNrResponse")]
        int AngebotNr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/AngebotNr", ReplyAction="http://tempuri.org/MassServis/AngebotNrResponse")]
        System.Threading.Tasks.Task<int> AngebotNrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaPrimljenihPoruka", ReplyAction="http://tempuri.org/MassServis/ListaPrimljenihPorukaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.tbl_poruka_primljene> ListaPrimljenihPoruka(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaPrimljenihPoruka", ReplyAction="http://tempuri.org/MassServis/ListaPrimljenihPorukaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.tbl_poruka_primljene>> ListaPrimljenihPorukaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaPoslanihPoruka", ReplyAction="http://tempuri.org/MassServis/ListaPoslanihPorukaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.tbl_poruka_poslane> ListaPoslanihPoruka(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaPoslanihPoruka", ReplyAction="http://tempuri.org/MassServis/ListaPoslanihPorukaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.tbl_poruka_poslane>> ListaPoslanihPorukaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/PosaljiPoruku", ReplyAction="http://tempuri.org/MassServis/PosaljiPorukuResponse")]
        void PosaljiPoruku(int primio, int poslao, string predmet, string naslov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/PosaljiPoruku", ReplyAction="http://tempuri.org/MassServis/PosaljiPorukuResponse")]
        System.Threading.Tasks.Task PosaljiPorukuAsync(int primio, int poslao, string predmet, string naslov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaKupacaSearch", ReplyAction="http://tempuri.org/MassServis/ListaKupacaSearchResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.kunden> ListaKupacaSearch(int broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaKupacaSearch", ReplyAction="http://tempuri.org/MassServis/ListaKupacaSearchResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.kunden>> ListaKupacaSearchAsync(int broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getMaterijal", ReplyAction="http://tempuri.org/MassServis/getMaterijalResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.materijal> getMaterijal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getMaterijal", ReplyAction="http://tempuri.org/MassServis/getMaterijalResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.materijal>> getMaterijalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getProdukt", ReplyAction="http://tempuri.org/MassServis/getProduktResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt> getProdukt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getProdukt", ReplyAction="http://tempuri.org/MassServis/getProduktResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt>> getProduktAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getPovrsinaByMaterijal", ReplyAction="http://tempuri.org/MassServis/getPovrsinaByMaterijalResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.oberflache> getPovrsinaByMaterijal(int matId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getPovrsinaByMaterijal", ReplyAction="http://tempuri.org/MassServis/getPovrsinaByMaterijalResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.oberflache>> getPovrsinaByMaterijalAsync(int matId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getDebljinaByProduktId", ReplyAction="http://tempuri.org/MassServis/getDebljinaByProduktIdResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.starke> getDebljinaByProduktId(int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getDebljinaByProduktId", ReplyAction="http://tempuri.org/MassServis/getDebljinaByProduktIdResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.starke>> getDebljinaByProduktIdAsync(int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getMatIdByName", ReplyAction="http://tempuri.org/MassServis/getMatIdByNameResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.materijal> getMatIdByName(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getMatIdByName", ReplyAction="http://tempuri.org/MassServis/getMatIdByNameResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.materijal>> getMatIdByNameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getProIdByName", ReplyAction="http://tempuri.org/MassServis/getProIdByNameResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt> getProIdByName(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getProIdByName", ReplyAction="http://tempuri.org/MassServis/getProIdByNameResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt>> getProIdByNameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getDebljinaIdByName", ReplyAction="http://tempuri.org/MassServis/getDebljinaIdByNameResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.starke> getDebljinaIdByName(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getDebljinaIdByName", ReplyAction="http://tempuri.org/MassServis/getDebljinaIdByNameResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.starke>> getDebljinaIdByNameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaEventaMitarbeiter", ReplyAction="http://tempuri.org/MassServis/ListaEventaMitarbeiterResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.mit_kalendar> ListaEventaMitarbeiter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaEventaMitarbeiter", ReplyAction="http://tempuri.org/MassServis/ListaEventaMitarbeiterResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.mit_kalendar>> ListaEventaMitarbeiterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UnesiEventMitarbeiter", ReplyAction="http://tempuri.org/MassServis/UnesiEventMitarbeiterResponse")]
        void UnesiEventMitarbeiter(Mass.Data.mit_kalendar mit_kalendar, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/UnesiEventMitarbeiter", ReplyAction="http://tempuri.org/MassServis/UnesiEventMitarbeiterResponse")]
        System.Threading.Tasks.Task UnesiEventMitarbeiterAsync(Mass.Data.mit_kalendar mit_kalendar, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getMaterijalByID", ReplyAction="http://tempuri.org/MassServis/getMaterijalByIDResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.artikl> getMaterijalByID(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getMaterijalByID", ReplyAction="http://tempuri.org/MassServis/getMaterijalByIDResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.artikl>> getMaterijalByIDAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getMaterialPrice", ReplyAction="http://tempuri.org/MassServis/getMaterialPriceResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_price_ViewResult> getMaterialPrice(int idMat, int idArt, string valStark, string valOber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getMaterialPrice", ReplyAction="http://tempuri.org/MassServis/getMaterialPriceResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_price_ViewResult>> getMaterialPriceAsync(int idMat, int idArt, string valStark, string valOber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getProduktIdByName", ReplyAction="http://tempuri.org/MassServis/getProduktIdByNameResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt> getProduktIdByName(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getProduktIdByName", ReplyAction="http://tempuri.org/MassServis/getProduktIdByNameResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt>> getProduktIdByNameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getMaterijalIDName", ReplyAction="http://tempuri.org/MassServis/getMaterijalIDNameResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.artikl> getMaterijalIDName(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/getMaterijalIDName", ReplyAction="http://tempuri.org/MassServis/getMaterijalIDNameResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.artikl>> getMaterijalIDNameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaMitKalendar", ReplyAction="http://tempuri.org/MassServis/ListaMitKalendarResponse")]
        System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_MitKalendar_ViewResult> ListaMitKalendar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassServis/ListaMitKalendar", ReplyAction="http://tempuri.org/MassServis/ListaMitKalendarResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_MitKalendar_ViewResult>> ListaMitKalendarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MassServisChannel : Desktop.Service.MassServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MassServisClient : System.ServiceModel.ClientBase<Desktop.Service.MassServis>, Desktop.Service.MassServis {
        
        public MassServisClient() {
        }
        
        public MassServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MassServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MassServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MassServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int LoginValidacija(string username, string pass) {
            return base.Channel.LoginValidacija(username, pass);
        }
        
        public System.Threading.Tasks.Task<int> LoginValidacijaAsync(string username, string pass) {
            return base.Channel.LoginValidacijaAsync(username, pass);
        }
        
        public void UnesiDobavljaca(Mass.Data.lieferant dobavljac) {
            base.Channel.UnesiDobavljaca(dobavljac);
        }
        
        public System.Threading.Tasks.Task UnesiDobavljacaAsync(Mass.Data.lieferant dobavljac) {
            return base.Channel.UnesiDobavljacaAsync(dobavljac);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.lieferant> ListaDobavljaca() {
            return base.Channel.ListaDobavljaca();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.lieferant>> ListaDobavljacaAsync() {
            return base.Channel.ListaDobavljacaAsync();
        }
        
        public void ObrisiDobavljaca(int brDobavljaca) {
            base.Channel.ObrisiDobavljaca(brDobavljaca);
        }
        
        public System.Threading.Tasks.Task ObrisiDobavljacaAsync(int brDobavljaca) {
            return base.Channel.ObrisiDobavljacaAsync(brDobavljaca);
        }
        
        public void UpdateDobavljac(Mass.Data.lieferant d) {
            base.Channel.UpdateDobavljac(d);
        }
        
        public System.Threading.Tasks.Task UpdateDobavljacAsync(Mass.Data.lieferant d) {
            return base.Channel.UpdateDobavljacAsync(d);
        }
        
        public void UnesiRadnika(
                    int broj, 
                    int titula, 
                    string ime, 
                    string prezime, 
                    string adresa, 
                    string tel1, 
                    string tel2, 
                    string mobitel, 
                    string fax, 
                    string skype, 
                    string email, 
                    float zarada, 
                    float satnica, 
                    string odmor, 
                    string odmor_na, 
                    float broj_plate, 
                    string bolovanje, 
                    string banka, 
                    string blz, 
                    string bic, 
                    string KtoNr, 
                    string Iban, 
                    string vlasnik, 
                    string biljeske, 
                    System.DateTime datum, 
                    int id) {
            base.Channel.UnesiRadnika(broj, titula, ime, prezime, adresa, tel1, tel2, mobitel, fax, skype, email, zarada, satnica, odmor, odmor_na, broj_plate, bolovanje, banka, blz, bic, KtoNr, Iban, vlasnik, biljeske, datum, id);
        }
        
        public System.Threading.Tasks.Task UnesiRadnikaAsync(
                    int broj, 
                    int titula, 
                    string ime, 
                    string prezime, 
                    string adresa, 
                    string tel1, 
                    string tel2, 
                    string mobitel, 
                    string fax, 
                    string skype, 
                    string email, 
                    float zarada, 
                    float satnica, 
                    string odmor, 
                    string odmor_na, 
                    float broj_plate, 
                    string bolovanje, 
                    string banka, 
                    string blz, 
                    string bic, 
                    string KtoNr, 
                    string Iban, 
                    string vlasnik, 
                    string biljeske, 
                    System.DateTime datum, 
                    int id) {
            return base.Channel.UnesiRadnikaAsync(broj, titula, ime, prezime, adresa, tel1, tel2, mobitel, fax, skype, email, zarada, satnica, odmor, odmor_na, broj_plate, bolovanje, banka, blz, bic, KtoNr, Iban, vlasnik, biljeske, datum, id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.mitarbeiter> ListaRadnika() {
            return base.Channel.ListaRadnika();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.mitarbeiter>> ListaRadnikaAsync() {
            return base.Channel.ListaRadnikaAsync();
        }
        
        public void UnesiKupca(Mass.Data.kunden kupac) {
            base.Channel.UnesiKupca(kupac);
        }
        
        public System.Threading.Tasks.Task UnesiKupcaAsync(Mass.Data.kunden kupac) {
            return base.Channel.UnesiKupcaAsync(kupac);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.user> ComboKorisnici() {
            return base.Channel.ComboKorisnici();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.user>> ComboKorisniciAsync() {
            return base.Channel.ComboKorisniciAsync();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.user> ComboKorisniciPoruke(int id) {
            return base.Channel.ComboKorisniciPoruke(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.user>> ComboKorisniciPorukeAsync(int id) {
            return base.Channel.ComboKorisniciPorukeAsync(id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.kunden> ListaKupaca() {
            return base.Channel.ListaKupaca();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.kunden>> ListaKupacaAsync() {
            return base.Channel.ListaKupacaAsync();
        }
        
        public void ObrisiKupca(int brKupca) {
            base.Channel.ObrisiKupca(brKupca);
        }
        
        public System.Threading.Tasks.Task ObrisiKupcaAsync(int brKupca) {
            return base.Channel.ObrisiKupcaAsync(brKupca);
        }
        
        public void UpdateKupac(Mass.Data.kunden k) {
            base.Channel.UpdateKupac(k);
        }
        
        public System.Threading.Tasks.Task UpdateKupacAsync(Mass.Data.kunden k) {
            return base.Channel.UpdateKupacAsync(k);
        }
        
        public void UnesiUsera(string Name, string LastName, string Email, string Telefon, bool Aktivan, string Slika, string Username, string Password, int UserType, bool Pocetna, string Licence) {
            base.Channel.UnesiUsera(Name, LastName, Email, Telefon, Aktivan, Slika, Username, Password, UserType, Pocetna, Licence);
        }
        
        public System.Threading.Tasks.Task UnesiUseraAsync(string Name, string LastName, string Email, string Telefon, bool Aktivan, string Slika, string Username, string Password, int UserType, bool Pocetna, string Licence) {
            return base.Channel.UnesiUseraAsync(Name, LastName, Email, Telefon, Aktivan, Slika, Username, Password, UserType, Pocetna, Licence);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_User_ViewResult> ListaUserView() {
            return base.Channel.ListaUserView();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_User_ViewResult>> ListaUserViewAsync() {
            return base.Channel.ListaUserViewAsync();
        }
        
        public System.Data.DataSet getUsersView() {
            return base.Channel.getUsersView();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getUsersViewAsync() {
            return base.Channel.getUsersViewAsync();
        }
        
        public void DeleteRadnik(int sifraRadnik) {
            base.Channel.DeleteRadnik(sifraRadnik);
        }
        
        public System.Threading.Tasks.Task DeleteRadnikAsync(int sifraRadnik) {
            return base.Channel.DeleteRadnikAsync(sifraRadnik);
        }
        
        public void UpdateRadnika(Mass.Data.mitarbeiter r, int id) {
            base.Channel.UpdateRadnika(r, id);
        }
        
        public System.Threading.Tasks.Task UpdateRadnikaAsync(Mass.Data.mitarbeiter r, int id) {
            return base.Channel.UpdateRadnikaAsync(r, id);
        }
        
        public Mass.Data.user VratiKorisnika(int id) {
            return base.Channel.VratiKorisnika(id);
        }
        
        public System.Threading.Tasks.Task<Mass.Data.user> VratiKorisnikaAsync(int id) {
            return base.Channel.VratiKorisnikaAsync(id);
        }
        
        public void EditujUsera(int idUser, string Name, string LastName, string Email, string Telefon, bool Aktivan, string Slika, string Username, string Password, int UserType, bool Pocetna, string Licence) {
            base.Channel.EditujUsera(idUser, Name, LastName, Email, Telefon, Aktivan, Slika, Username, Password, UserType, Pocetna, Licence);
        }
        
        public System.Threading.Tasks.Task EditujUseraAsync(int idUser, string Name, string LastName, string Email, string Telefon, bool Aktivan, string Slika, string Username, string Password, int UserType, bool Pocetna, string Licence) {
            return base.Channel.EditujUseraAsync(idUser, Name, LastName, Email, Telefon, Aktivan, Slika, Username, Password, UserType, Pocetna, Licence);
        }
        
        public void UpdateKorisnik(Mass.Data.user k) {
            base.Channel.UpdateKorisnik(k);
        }
        
        public System.Threading.Tasks.Task UpdateKorisnikAsync(Mass.Data.user k) {
            return base.Channel.UpdateKorisnikAsync(k);
        }
        
        public void DeleteUser(int idUser) {
            base.Channel.DeleteUser(idUser);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int idUser) {
            return base.Channel.DeleteUserAsync(idUser);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.mitarbeiter> PretraziRadnika(string ime) {
            return base.Channel.PretraziRadnika(ime);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.mitarbeiter>> PretraziRadnikaAsync(string ime) {
            return base.Channel.PretraziRadnikaAsync(ime);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.lieferant> PretraziDobavljaca(string ime) {
            return base.Channel.PretraziDobavljaca(ime);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.lieferant>> PretraziDobavljacaAsync(string ime) {
            return base.Channel.PretraziDobavljacaAsync(ime);
        }
        
        public void changeUserPocetnaOrAktivan(int tip, int idUser, bool value) {
            base.Channel.changeUserPocetnaOrAktivan(tip, idUser, value);
        }
        
        public System.Threading.Tasks.Task changeUserPocetnaOrAktivanAsync(int tip, int idUser, bool value) {
            return base.Channel.changeUserPocetnaOrAktivanAsync(tip, idUser, value);
        }
        
        public void ChangeWorkerStatus(int idRadnika, bool status) {
            base.Channel.ChangeWorkerStatus(idRadnika, status);
        }
        
        public System.Threading.Tasks.Task ChangeWorkerStatusAsync(int idRadnika, bool status) {
            return base.Channel.ChangeWorkerStatusAsync(idRadnika, status);
        }
        
        public void unesiBug(string bugText, int idUser, bool status, string date) {
            base.Channel.unesiBug(bugText, idUser, status, date);
        }
        
        public System.Threading.Tasks.Task unesiBugAsync(string bugText, int idUser, bool status, string date) {
            return base.Channel.unesiBugAsync(bugText, idUser, status, date);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.bug> ListaBugova() {
            return base.Channel.ListaBugova();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.bug>> ListaBugovaAsync() {
            return base.Channel.ListaBugovaAsync();
        }
        
        public void changeBugStatus(string datum, bool statusValue) {
            base.Channel.changeBugStatus(datum, statusValue);
        }
        
        public System.Threading.Tasks.Task changeBugStatusAsync(string datum, bool statusValue) {
            return base.Channel.changeBugStatusAsync(datum, statusValue);
        }
        
        public void DeleteBug(string datum) {
            base.Channel.DeleteBug(datum);
        }
        
        public System.Threading.Tasks.Task DeleteBugAsync(string datum) {
            return base.Channel.DeleteBugAsync(datum);
        }
        
        public int MitarbeiterNr() {
            return base.Channel.MitarbeiterNr();
        }
        
        public System.Threading.Tasks.Task<int> MitarbeiterNrAsync() {
            return base.Channel.MitarbeiterNrAsync();
        }
        
        public int LieferantNr() {
            return base.Channel.LieferantNr();
        }
        
        public System.Threading.Tasks.Task<int> LieferantNrAsync() {
            return base.Channel.LieferantNrAsync();
        }
        
        public int KundenNr() {
            return base.Channel.KundenNr();
        }
        
        public System.Threading.Tasks.Task<int> KundenNrAsync() {
            return base.Channel.KundenNrAsync();
        }
        
        public int AngebotNr() {
            return base.Channel.AngebotNr();
        }
        
        public System.Threading.Tasks.Task<int> AngebotNrAsync() {
            return base.Channel.AngebotNrAsync();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.tbl_poruka_primljene> ListaPrimljenihPoruka(int id) {
            return base.Channel.ListaPrimljenihPoruka(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.tbl_poruka_primljene>> ListaPrimljenihPorukaAsync(int id) {
            return base.Channel.ListaPrimljenihPorukaAsync(id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.tbl_poruka_poslane> ListaPoslanihPoruka(int id) {
            return base.Channel.ListaPoslanihPoruka(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.tbl_poruka_poslane>> ListaPoslanihPorukaAsync(int id) {
            return base.Channel.ListaPoslanihPorukaAsync(id);
        }
        
        public void PosaljiPoruku(int primio, int poslao, string predmet, string naslov) {
            base.Channel.PosaljiPoruku(primio, poslao, predmet, naslov);
        }
        
        public System.Threading.Tasks.Task PosaljiPorukuAsync(int primio, int poslao, string predmet, string naslov) {
            return base.Channel.PosaljiPorukuAsync(primio, poslao, predmet, naslov);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.kunden> ListaKupacaSearch(int broj) {
            return base.Channel.ListaKupacaSearch(broj);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.kunden>> ListaKupacaSearchAsync(int broj) {
            return base.Channel.ListaKupacaSearchAsync(broj);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.materijal> getMaterijal() {
            return base.Channel.getMaterijal();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.materijal>> getMaterijalAsync() {
            return base.Channel.getMaterijalAsync();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt> getProdukt() {
            return base.Channel.getProdukt();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt>> getProduktAsync() {
            return base.Channel.getProduktAsync();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.oberflache> getPovrsinaByMaterijal(int matId) {
            return base.Channel.getPovrsinaByMaterijal(matId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.oberflache>> getPovrsinaByMaterijalAsync(int matId) {
            return base.Channel.getPovrsinaByMaterijalAsync(matId);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.starke> getDebljinaByProduktId(int prodId) {
            return base.Channel.getDebljinaByProduktId(prodId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.starke>> getDebljinaByProduktIdAsync(int prodId) {
            return base.Channel.getDebljinaByProduktIdAsync(prodId);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.materijal> getMatIdByName(string value) {
            return base.Channel.getMatIdByName(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.materijal>> getMatIdByNameAsync(string value) {
            return base.Channel.getMatIdByNameAsync(value);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt> getProIdByName(string value) {
            return base.Channel.getProIdByName(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt>> getProIdByNameAsync(string value) {
            return base.Channel.getProIdByNameAsync(value);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.starke> getDebljinaIdByName(string value) {
            return base.Channel.getDebljinaIdByName(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.starke>> getDebljinaIdByNameAsync(string value) {
            return base.Channel.getDebljinaIdByNameAsync(value);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.mit_kalendar> ListaEventaMitarbeiter() {
            return base.Channel.ListaEventaMitarbeiter();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.mit_kalendar>> ListaEventaMitarbeiterAsync() {
            return base.Channel.ListaEventaMitarbeiterAsync();
        }
        
        public void UnesiEventMitarbeiter(Mass.Data.mit_kalendar mit_kalendar, int id) {
            base.Channel.UnesiEventMitarbeiter(mit_kalendar, id);
        }
        
        public System.Threading.Tasks.Task UnesiEventMitarbeiterAsync(Mass.Data.mit_kalendar mit_kalendar, int id) {
            return base.Channel.UnesiEventMitarbeiterAsync(mit_kalendar, id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.artikl> getMaterijalByID(int value) {
            return base.Channel.getMaterijalByID(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.artikl>> getMaterijalByIDAsync(int value) {
            return base.Channel.getMaterijalByIDAsync(value);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_price_ViewResult> getMaterialPrice(int idMat, int idArt, string valStark, string valOber) {
            return base.Channel.getMaterialPrice(idMat, idArt, valStark, valOber);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_price_ViewResult>> getMaterialPriceAsync(int idMat, int idArt, string valStark, string valOber) {
            return base.Channel.getMaterialPriceAsync(idMat, idArt, valStark, valOber);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt> getProduktIdByName(string value) {
            return base.Channel.getProduktIdByName(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.produkt>> getProduktIdByNameAsync(string value) {
            return base.Channel.getProduktIdByNameAsync(value);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.artikl> getMaterijalIDName(string value) {
            return base.Channel.getMaterijalIDName(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.artikl>> getMaterijalIDNameAsync(string value) {
            return base.Channel.getMaterijalIDNameAsync(value);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_MitKalendar_ViewResult> ListaMitKalendar() {
            return base.Channel.ListaMitKalendar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Mass.Data.p_get_MitKalendar_ViewResult>> ListaMitKalendarAsync() {
            return base.Channel.ListaMitKalendarAsync();
        }
    }
}
