<?xml version="1.0" encoding="utf-8"?><Database Name="maas_faktura" Class="DataBaseModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MAAG\SQLEXPRESS;Initial Catalog=maas_faktura;Persist Security Info=True;User ID=test" SettingsObjectName="Mass.Data.Properties.Settings" SettingsPropertyName="maas_fakturaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.akonto" Member="akontos">
    <Type Name="akonto">
      <Column Name="idakonto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ab" Type="System.String" DbType="NChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="iduser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vrijeme" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="suma" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="akontonr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.zemlja_porijekla_inv" Member="zemlja_porijekla_invs">
    <Type Name="zemlja_porijekla_inv">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="naziv" Type="System.String" DbType="NChar(450)" CanBeNull="true" />
      <Column Name="slika" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.angebot" Member="angebots">
    <Type Name="angebot">
      <Column Name="idangebot" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="iduser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="angebotnr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kundenr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kunde" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="anfragen" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="angefragt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="preisn" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="preisb" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="resonanz" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="nachgefragt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="resonanz1" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="geschrieben" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="folder" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="zeichnung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="privat" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="handy" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="porez" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.anzahlungen" Member="anzahlungens">
    <Type Name="anzahlungen">
      <Column Name="idplacanje" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ab" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="uplatio" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="nacin" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="iduser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.artikl" Member="artikls">
    <Type Name="artikl">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="materijal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="naziv" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="slika" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="svrha" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="zemlja_porijekla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vrsta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sinonimi" Type="System.String" DbType="NChar(2000)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
      <Column Name="kratki_opis" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="tehnicki_detalji" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="podgrupa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="aktivan" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.auftrage" Member="auftrages">
    <Type Name="auftrage">
      <Column Name="ab" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="kundenr" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kunde" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="ort" Type="System.String" DbType="NChar(25)" CanBeNull="true" />
      <Column Name="anzahlung" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="preisb" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="preisn" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="angebotnr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="geschrieben" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lat" Type="System.Decimal" DbType="Decimal(10,8)" CanBeNull="true" />
      <Column Name="lng" Type="System.Decimal" DbType="Decimal(10,8)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reklamation" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="anztime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ort1" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="[print]" Member="print" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nabavka" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="anzahlungbei" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.beschtelung" Member="beschtelungs">
    <Type Name="beschtelung">
      <Column Name="idbeschtelung" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ab" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idproizvod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="qm" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="lieferant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="woche" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cijena" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="naruceno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="einheit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lange" Type="System.String" DbType="NChar(45)" CanBeNull="true" />
      <Column Name="breit" Type="System.String" DbType="NChar(45)" CanBeNull="true" />
      <Column Name="broj_ploce" Type="System.String" DbType="NChar(45)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.brojevi_racuna" Member="brojevi_racunas">
    <Type Name="brojevi_racuna">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="brojR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.bug" Member="bugs">
    <Type Name="bug">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bug" Member="bug1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ca_produkt" Member="ca_produkts">
    <Type Name="ca_produkt">
      <Column Name="iproizvod" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fertigung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="anlieferung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="abholung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="aufmas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="montage" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.cijena_artikl_inv" Member="cijena_artikl_invs">
    <Type Name="cijena_artikl_inv">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_artikl" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vrsta_cijene" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="iznos" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="napomena" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.einheit" Member="einheits">
    <Type Name="einheit">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="jedinica" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kalendar" Member="kalendars">
    <Type Name="kalendar">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ort" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="opis" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="datum1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="aktiv" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kunden" Member="kundens">
    <Type Name="kunden">
      <Column Name="idKunde" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="kundeNr" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="suchbegriff" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="vorname" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="[l-plz-ort]" Member="l_plz_ort" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="gruppe" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="freifeld1" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="name2" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="strasse" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="tel1" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="tel2" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="lk" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="vorlage_am" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="vorlage_anlass" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="VKPreisgr" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="zahlungin" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="skonto" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="skontotage" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="vertreter" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="ufragssperre" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="anreden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lieferadresse" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="rechnungsadresse" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="email2" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="internet" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="kundetype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="steuer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="zahlweise" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="zahl_beding" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="kundenbewertung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="notiz" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="titel" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="land" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="zahlbar" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="rabat" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="adresse2" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="stadt" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="anredeans" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="anssprechepartner" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="notiz_route" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.lieferant" Member="lieferants">
    <Type Name="lieferant">
      <Column Name="idLief" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lieferantNr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="anrede" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vorname" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="adresse" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="tel1" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="tel2" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="handy" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="skype" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="bank" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="BLZ" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="KtoNr" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="BIC" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="IBAN" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="kontoinhaber" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="notiz" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="umsatz" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="zahlweise" Type="System.String" DbType="NChar(70)" CanBeNull="true" />
      <Column Name="land" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="branche" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="skonto" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="tage" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="zahlbar" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="rabat" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="bankeinzug" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stauer" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.material_inventar" Member="material_inventars">
    <Type Name="material_inventar">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sifra_materiala" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="vrsta_materiala" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="debljina" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="struktura" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="namjena" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="dobavljac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kolicina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="defekt" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="slika" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="sektor" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="[user]" Member="user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="geschrieben" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="material_name" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="width" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="height" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="lager" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="notiz" Type="System.String" DbType="NChar(300)" CanBeNull="true" />
      <Column Name="reklamation" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.materijal" Member="materijals">
    <Type Name="materijal">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="naziv" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mit_kalendar" Member="mit_kalendars">
    <Type Name="mit_kalendar">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="datum1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="odobreno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pogledano" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="notiz" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.mitarbeiter" Member="mitarbeiters">
    <Type Name="mitarbeiter">
      <Column Name="idMit" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mitarbeiterNr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="anrede" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vorname" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="adresse" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="tel1" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="tel2" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="handy" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="skype" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="gehalt" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="stundenlohn" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="urlaub_ist" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="urlaub_soll" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="anzahl_gehalter" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="wochen_std" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="krankheit" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="bank" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="BLZ" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="KtoNr" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="BIC" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="IBAN" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="kontoinhaber" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="notiz" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="datum" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="folder" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.nach_details" Member="nach_details">
    <Type Name="nach_detail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idangebot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="angebotnr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kundenr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="notiz" Type="System.String" DbType="NChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.nachverfolgung" Member="nachverfolgungs">
    <Type Name="nachverfolgung">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="angebotnr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kundenr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="interval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="iduser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NChar(45)" CanBeNull="true" />
      <Column Name="broj_slanja" Type="System.String" DbType="NChar(45)" CanBeNull="true" />
      <Column Name="datum_prvog_slanja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="datum_drugog_slanja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="interval2" Type="System.String" DbType="NChar(45)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.oberflache" Member="oberflaches">
    <Type Name="oberflache">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="materijal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pov" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pages" Member="pages">
    <Type Name="page">
      <Column Name="idPage" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="domena" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.podgrupa_inv" Member="podgrupa_invs">
    <Type Name="podgrupa_inv">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="naziv" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="opis" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.podpozicija" Member="podpozicijas">
    <Type Name="podpozicija">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_p" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="naziv" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="jedinica" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="cijena" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="standard" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.pozicija" Member="pozicijas">
    <Type Name="pozicija">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="naziv" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.produkt" Member="produkts">
    <Type Name="produkt">
      <Column Name="idprodukt" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="naziv" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.produkt_SEO_inv" Member="produkt_SEO_invs">
    <Type Name="produkt_SEO_inv">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="primjena" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="web_stranica" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="head" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="rs_desc" Type="System.String" DbType="NChar(600)" CanBeNull="true" />
      <Column Name="rw_desc" Type="System.String" DbType="NChar(600)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.produktion" Member="produktions">
    <Type Name="produktion">
      <Column Name="idproduktion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idproizvod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="zeichnung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="anlieferung" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="abholung" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="aufmas" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="montage" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="zeichO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="aufmasO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="postversand" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fertigung" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="materialbeschafung" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.proizvod" Member="proizvods">
    <Type Name="proizvod">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="angebotnr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="materijal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="materijaltype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="oberflache" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="materijal2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="materijaltype2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="oberflache2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="starke" Type="System.String" DbType="NChar(25)" CanBeNull="true" />
      <Column Name="gehrung" Type="System.String" DbType="NChar(25)" CanBeNull="true" />
      <Column Name="einh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="menge" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="einhpreis" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="rabatt" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="alternative" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lange" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="breit" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="preis" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="stuck" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.rechnung_a" Member="rechnung_as">
    <Type Name="rechnung_a">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ab" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="angebotnr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kundenr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kunde" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="preis" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="mwst" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[user]" Member="user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="aktivan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="rechNr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="akonto" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.rechnung_b" Member="rechnung_bs">
    <Type Name="rechnung_b">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rechnr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kundennr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="mwst" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="betrag" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[user]" Member="user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="aktivan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pdf" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="steuer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.rechnung_b_pozicije" Member="rechnung_b_pozicijes">
    <Type Name="rechnung_b_pozicije">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rechnr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bezeichnung" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="einheit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="menge" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="einzelpreis" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="rabatt" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="gesamtpreis" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.reklamation" Member="reklamations">
    <Type Name="reklamation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ab" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idprodukt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="suma" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="radnik" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="notice" Type="System.String" DbType="NChar(300)" CanBeNull="true" />
      <Column Name="[file]" Member="file" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.route_kalendar" Member="route_kalendars">
    <Type Name="route_kalendar">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="iduser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dan" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="datum_pocetka" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="datum_kraja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="opis" Type="System.String" DbType="NChar(1000)" CanBeNull="true" />
      <Column Name="woche" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RouteTech" Member="RouteTeches">
    <Type Name="RouteTech">
      <Column Name="idProduktion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idTech" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.starke" Member="starkes">
    <Type Name="starke">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idprodukt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="starke" Member="starke1" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_poruka_poslane" Member="tbl_poruka_poslanes">
    <Type Name="tbl_poruka_poslane">
      <Column Name="id_poruka_poslane" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="poslao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="primio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="predmet" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="naslov" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Association Name="user_tbl_poruka_poslane" Member="user" ThisKey="poslao" OtherKey="idUser" Type="user" IsForeignKey="true" />
      <Association Name="user_tbl_poruka_poslane1" Member="user1" ThisKey="primio" OtherKey="idUser" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_poruka_primljene" Member="tbl_poruka_primljenes">
    <Type Name="tbl_poruka_primljene">
      <Column Name="id_poruka_primljene" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="poslao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="primio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="procitano" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="predmet" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="naslov" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Association Name="user_tbl_poruka_primljene" Member="user" ThisKey="poslao" OtherKey="idUser" Type="user" IsForeignKey="true" />
      <Association Name="user_tbl_poruka_primljene1" Member="user1" ThisKey="primio" OtherKey="idUser" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="sessionId" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="userType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="telefon" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="slika" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
      <Column Name="startseit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="user_tbl_poruka_poslane" Member="tbl_poruka_poslanes" ThisKey="idUser" OtherKey="poslao" Type="tbl_poruka_poslane" />
      <Association Name="user_tbl_poruka_poslane1" Member="tbl_poruka_poslanes1" ThisKey="idUser" OtherKey="primio" Type="tbl_poruka_poslane" />
      <Association Name="user_tbl_poruka_primljene" Member="tbl_poruka_primljenes" ThisKey="idUser" OtherKey="poslao" Type="tbl_poruka_primljene" />
      <Association Name="user_tbl_poruka_primljene1" Member="tbl_poruka_primljenes1" ThisKey="idUser" OtherKey="primio" Type="tbl_poruka_primljene" />
    </Type>
  </Table>
  <Table Name="dbo.user_licence" Member="user_licences">
    <Type Name="user_licence">
      <Column Name="id_licence" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="active" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vrsta_cijene_inv" Member="vrsta_cijene_invs">
    <Type Name="vrsta_cijene_inv">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="naziv" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
      <Column Name="debljina" Type="System.String" DbType="NChar(45)" CanBeNull="true" />
      <Column Name="mjerna_jedinica" Type="System.String" DbType="NChar(45)" CanBeNull="true" />
      <Column Name="koeficijent1" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
      <Column Name="koeficijent2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="napomena_porez" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
      <Column Name="prikazati_na" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="angebot_koeficijent" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="opis" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
      <Column Name="napomena" Type="System.String" DbType="NChar(600)" CanBeNull="true" />
      <Column Name="active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="starke" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="oberflache" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.web_stranice_inv" Member="web_stranice_invs">
    <Type Name="web_stranice_inv">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="naziv" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.p_get_User_ViewResult" Member="p_get_User_ViewResults">
    <Type Name="p_get_User_ViewResult">
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="sessionId" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="userType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="telefon" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="slika" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
      <Column Name="startseit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>